name: Desktop SSH

on:
  workflow_dispatch:

jobs:
  desktop:
    runs-on: ubuntu-latest
    steps:
      - name: ssh <random-session>@uptermd.upterm.dev
        background: true
        uses: owenthereal/action-upterm@v1
        with:
          detached: true

      - name: Desktop URL https://<random-subdomain>.trycloudflare.com / Stop with curl x or x/ in Address Bar
        run: sleep 3600
