name: Run Webtop (Browser Desktop)

on:
  workflow_dispatch:

jobs:
  webtop:
    runs-on: ubuntu-latest
    steps:
      - parallel:
        - name: Start Webtop Container
          run: |
            docker run -d \
              --security-opt seccomp=unconfined \
              -p 3000:3000 \
              -p 3001:3001 \
              --shm-size=1gb \
              --restart unless-stopped \
              ghcr.io/linuxserver/webtop

        - name: Desktop URL https://<random-subdomain>.trycloudflare.com
          run: |
            wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
            sudo dpkg -i cloudflared-linux-amd64.deb
            cloudflared tunnel --url http://localhost:3000